// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as AboutRoute from "@/app/about/page.info";
import * as PostsRoute from "@/app/posts/page.info";
import * as PostsPostIDRoute from "@/app/posts/[postID]/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const About = makeRoute(
  "/about",
  {
    ...defaultInfo,
    ...AboutRoute.Route
  }
);
export const Posts = makeRoute(
  "/posts",
  {
    ...defaultInfo,
    ...PostsRoute.Route
  }
);
export const PostsPostID = makeRoute(
  "/posts/[postID]",
  {
    ...defaultInfo,
    ...PostsPostIDRoute.Route
  }
);

